### ISSUE TITLE
Network or server error occurred.

### ISSUE THREAD

**Issue by gemarsh** [astrowings/SmartThings#2]
I was able to create the smartapp and it saved without issue however, when I attempt to run it I receive the error "Network or server error occurred."  What would you suggest I try to troubleshoot.

**Comment by astrowings** [comment]
Which smartapp? Where do get the error; in the SmartThings app? Which SmartThings app (old/new) are you using? Which platform?

**Comment by gemarsh** [comment]
It's the Block Heater one.    I put the code in my smartapps on smartthings, published it when I access it via my smartapps in the legacy app it shows "Something's Wrong.  We can't load your screen right now.  When I try it on the new smarthings app it gives the error "Network or server error occurred.  Try again later."

**Comment by astrowings** [comment]
I'm afraid there isn't much I can do to help with this one as this seems to be related to a SmartThings connectivity issue or something with your SmartThings app installation or mobile device. I had a quick look on the forums, and there are a few people complaining about this same issue and various suggestions to try to resolve it such as trying to rename the smartapp on installation, rebooting the device, or even as far as re-installing SmartThings completely. Have a look at https://community.smartthings.com for some suggestions and input from other users with the same problem.

Sorry there isn't much else I can do. Once you get it working, don't hesitate to get in touch if you encounter issues with the smartapp or if you'd like to see additional features.
